### ISSUE TITLE
Extra port number in address

### ISSUE THREAD

**Issue by azhiltsov** [jjneely/buckytools#16]
It introduced after the 8192e5497cfcf69b6187101c149bddbd2ada6394

$ bucky delete -h 10.20.30.40:4242 test1.test2.wisp1
Deleting 1 metrics on 10.20:30:40:4242...
Error communicating: dial tcp: too many colons in address 10.20:30:40:4242:4242

**Comment by jjneely** [comment]
This should be fixed on master at this point.  Re-open if you hit similar issues.
