### ISSUE TITLE
Build from source on debian 8 seems broken

### ISSUE THREAD

**Issue by ra-dft** [jjneely/buckytools#22]
Hello,

Super excited to see that you included fnv1a_ch in your latest build.  However, I'm running into some errors during _go install ./..._ .

`buckytools # go install ./...
`# github.com/golang/snappy`
` ../../golang/snappy/decode_amd64.s:10 6a: No such file or directory: textflag.h`
`# github.com/kisielk/og-rek`
`../../kisielk/og-rek/ogorek.go:680: reflect.TypeOf(key).Comparable undefined (type reflect.Type has no field or method Comparable)`
`../../kisielk/og-rek/ogorek.go:873: reflect.TypeOf(k).Comparable undefined (type reflect.Type has no field or method Comparable)`
`../../kisielk/og-rek/ogorek.go:900: reflect.TypeOf(key).Comparable undefined (type reflect.Type has no > field or method Comparable)`
`# github.com/jjneely/buckytools/vendor/github.com/kisielk/og-rek`
`vendor/github.com/kisielk/og-rek/ogorek.go:680: reflect.TypeOf(key).Comparable undefined (type reflect.Type has no field or method Comparable)`
` vendor/github.com/kisielk/og-rek/ogorek.go:873: reflect.TypeOf(k).Comparable undefined (type reflect.Type has no field or method Comparable)`
`vendor/github.com/kisielk/og-rek/ogorek.go:900: reflect.TypeOf(key).Comparable undefined (type reflect.Type has no field or method Comparable)`
`# github.com/jjneely/buckytools/vendor/github.com/golang/snappy`
` vendor/github.com/golang/snappy/decode_amd64.s:10 6a: No such file or directory: textflag.h`

Now bare with me, I'm a little new to building go code from source.  Currently these machines have 

> buckytools # go version
go version go1.3.3 linux/amd64

**Comment by ra-dft** [comment]
I went the gbp path and have run into this now:

>dh_auto_build: go install -v github.com/jjneely/buckytools github.com/jjneely/buckytools/cmd/bucky github.com/jjneely/buckytools/cmd/bucky-fill github.com/jjneely/buckytools/cmd/bucky-isempty > github.com/jjneely/buckytools/cmd/bucky-pickle-relay github.com/jjneely/buckytools/cmd/bucky-sparsify github.com/jjneely/buckytools/cmd/buckyd github.com/jjneely/buckytools/cmd/findhash github.com/jjneely/buckytools/cmd/gentestmetrics github.com/jjneely/buckytools/fill github.com/jjneely/buckytools/hashing github.com/jjneely/buckytools/lock github.com/jjneely/buckytools/metrics github.com/jjneely/buckytools/vendor/github.com/golang/crypto/ssh/terminal github.com/jjneely/buckytools/vendor/github.com/golang/snappy github.com/jjneely/buckytools/vendor/github.com/kisielk/og-rek github.com/jjneely/buckytools/vendor/github.com/pborman/uuid github.com/jjneely/buckytools/whisper returned exit code 1
debian/rules:14: recipe for target 'build' failed
make: *** [build] Error 1
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc -i -I failed
>gbp:error: 'debuild -i -I' failed: it exited with 29

**Comment by jjneely** [comment]
Go 1.3 is really old at this point.  I know I haven't tested with anything near there in a while.  I've been building lately with 1.8.3.

**Comment by ra-dft** [comment]
@jjneely Thank you for this nugget.  I'm off to the races now.
