### ISSUE TITLE
Question: bucky re-balance jump_fnv1a

### ISSUE THREAD

**Issue by cjagus** [jjneely/buckytools#31]
I tried to rebalance a single jump_fnv1a carbon instance by adding two more, initial one was having a disk size of 6gb. 

After the rebalance:
`instance1 = 2.1gb 
instance2 = 1.6 gb
instande3 = 1.6 gb`

Is this an expected behaviour? ( considering jump hash has a much better balancing b/w servers)

I tried below command to do the same. 

`bucky rebalance -delete -h instance1 :4242 -w 25 2>&1 | tee rebalance.log` [using bucky/buckyd 0.4.0]

**Comment by jjneely** [comment]
The hashing is based on the metric name (not the size/retention of the metric), but in most cases I'd expect the number of wsp files to be really close throughout the Graphite cluster when using the jump hash.

Run `bucky inconsistent` and see what it says.
