### ISSUE TITLE
Push your changes to go-whisper to upstream

### ISSUE THREAD

**Issue by Civil** [jjneely/buckytools#4]
I think everybody will benefit if you'll push your changes of whisper to upstream.

**Comment by deniszh** [comment]
https://github.com/robyoung/go-whisper/pull/11

**Comment by deniszh** [comment]
It seems that @robyoung is not very active now. That's why @lomik has also own fork of go-whisper https://github.com/lomik/go-whisper for go-carbon...

**Comment by Civil** [comment]
Maybe then it's better to rebase upon Lomik's version of go-whisper and send him PRs for all the changes?

**Comment by jjneely** [comment]
Looks like most of my PRs have been merged upstream with Rob.

Outstanding:
* https://github.com/robyoung/go-whisper/pull/19

**Comment by robyoung** [comment]
@jjneely if you can add a test I will happily merge.
